### ISSUE TITLE
[Bug Report]: Problem with realmstatus

### ISSUE THREAD

**Issue by Blacky244-dev** [WoW-CMS/BlizzCMS#100]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

I have the problem when I add my realm to the webpage no matter if I do it via the webside or manually directly into the db that I get the error 

Server Status
An Error Was Encountered

Invalid DB Connection String

But I have entered my data correctly without running the webpage 

My mysqlserver is this:::  Community Mysql Server v8.31 64 bit

My webserver is         :::    IIs 10 on Win Server 2019

I hope someone can help me I am at my Latin at the end

### How can I reproduce the problem?

No i can this not reproduce 

### Screenshots

![Realmsite](https://user-images.githubusercontent.com/79584869/200951324-8c2157c4-22a9-4cee-8710-9ede3da8f458.png)

**Comment by sayghteight** [comment]
Hi, it is possible that you are placing something strange in the configuration of the realm, I will need you to check that the data provided in the config is correct.
