### ISSUE TITLE
🐛 [Bug Report]: Links to any uploaded images are broken

### ISSUE THREAD

**Issue by DavidBronzebeard** [WoW-CMS/BlizzCMS#104]
### BlizzCMS Version

Links to any uploaded images are broken

### Emulator

CMaNGOS

### PHP Version

PHP 7.4

### Operating system

Windows

### Web server

Apache

### Database

MySQL Server 8.0.31

### Description

Any uploaded image imports fine, but when viewed in the News article, Frontpage or Avatar section is just a broken link.

Apache access logs indicate a failure to find the images as the links requested include an additional uploads/ folder.

### How can I reproduce the problem?

Upload an account avatar or news article image.

### Screenshots

![image](https://user-images.githubusercontent.com/110580384/206814703-55527c4f-b8a0-41f9-8a4a-ba59f54ed699.png)

**Comment by DZywolf** [comment]
fixed with af634c3af7908cccbd190b00af8cd79edfd908a0 and cd7b5bc5b76ef3672d09ccec16db13faddf68e93
