### ISSUE TITLE
website installing linux🐛 [Bug Report]: 

### ISSUE THREAD

**Issue by drustcore** [WoW-CMS/BlizzCMS#114]
### BlizzCMS Version

last version

### Emulator

TrinityCore

### PHP Version

PHP 7.4

### Operating system

Linux

### Web server

Apache

### Database

mariadb

### What happened?

linux Folder is not writable, please enable mod_rewrite and set permissions how to fix this error?
[23:16]
eamod enabled alrdy

### How can the issue be reproduced?

idk

**Comment by Jean-Dv** [comment]
Maybe it's the linux folder permissions, you can check with "ls -la" that the user and group are with www-data?
