### ISSUE TITLE
🐛 [Bug Report]: password reset in 404

### ISSUE THREAD

**Issue by andsim** [WoW-CMS/BlizzCMS#117]
### BlizzCMS Version

beta 2

### Emulator

TrinityCore

### PHP Version

PHP 7.4

### Operating system

Windows

### Web server

Apache

### Database

MariaDB 11

### What happened?

reset password not work.. goes 404

### How can the issue be reproduced?

easy click on forgot your password?

**Comment by Jean-Dv** [comment]
The problem has been verified and everything works correctly.
Some problems that may arise with you:
- The cache is interrupting or saving wrong information, you can delete the information from the application/cache/* folder
- It is possible that the user does not exist for the system in the database, for this you can send us the error that you get in application/logs, when you activate the logs in application/config/config.php in line 228 changing the 0 to the 1, leaving in this way "$config['log_threshold'] = 1;"

![image](https://github.com/WoW-CMS/BlizzCMS/assets/72704457/475d67c5-9bc7-4feb-af27-4cae4a871328)

**Comment by andsim** [comment]
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2023-06-25 03:13:16 --> Page not found: 
ERROR - 2023-06-25 03:13:17 --> Page not found: 
ERROR - 2023-06-25 09:53:29 --> Page not found:

**Comment by andsim** [comment]
> Nothing happen with BlizzCMS v 1.21 ----> $config['log_threshold'] = 1; SMTP still doesn't work

wrong issues

**Comment by Jean-Dv** [comment]
Why route is "https://localhost.com/wow/forgot-password"?, You can try with "https://localhost.com/forgot-password"
Change localhost with your domain

**Comment by Jean-Dv** [comment]
You verified in admin panel, if page forgot-password is enabled? Is the only thing that occurs to me

**Comment by andsim** [comment]
cant access it wo know the password

**Comment by Jean-Dv** [comment]
In your database, search table "settings". And search "show forgot page", if is false then change to true.

**Comment by andsim** [comment]
ok it is working getting error or conform u get green box after fill

**Comment by Jean-Dv** [comment]
For the forgot password function, you need the account register with email, and need config correctly smtp server.

**Comment by andsim** [comment]
i had itr setup should be set before i upgrade
