### ISSUE TITLE
🐛 [Bug Report]: CMS V1.2.1 SMTP not work,config['sess_save_path'] error

### ISSUE THREAD

**Issue by tim3126** [WoW-CMS/BlizzCMS#118]
### BlizzCMS Version

1.2.1

### Emulator

AzerothCore

### PHP Version

PHP 8.0

### Operating system

Linux

### Web server

Apache

### Database

MySQL 5.7

### What happened?

1,SMTP 465  SSL   doesn't work ,can't send mail,no logs in application/log
2,config['sess_save_path'] error

### How can the issue be reproduced?

1,Installing v1.2.1, an error of config['sess_save_path'] error occurred during the installation:   message:mkdir() :invalid path fliename:drives/session_flies_drive.php  line number:137
2, It must be changed to: FCPATH.'cache/sess_save_path'; to open the website
3,After setting up smtp and set the password recovery function on, SMTP 465  SSL   doesn't work ,can't send mail,no logs in application/log, and the email cannot be sent, no email be received

### Screenshots

[https://tc.evewow.com/i/2023/06/26/nx2smw.png](url)

**Comment by sayghteight** [comment]
We are aware of this bug, we are working on fixing it. Sometimes this happens because the CMS is distributed for session by file and there are not enough permissions on that path.
