### ISSUE TITLE
🐛 [Bug Report]: Uploading a file exceeds the maximum size allowed

### ISSUE THREAD

**Issue by minzhicloud** [WoW-CMS/BlizzCMS#125]
### BlizzCMS Version

v2.0.0-beta.2

### Emulator

AzerothCore

### PHP Version

PHP 7.4

### Operating system

Linux

### Web server

Other

### Database

MySQL5.7

### What happened?

Unable to upload no matter how modified

### How can the issue be reproduced?

This problem occurs after uploading a module

### Screenshots

![111](https://github.com/WoW-CMS/BlizzCMS/assets/110570970/4afeb476-bb7f-4dae-9521-a6777eee9a76)

**Comment by DZywolf** [comment]
This error is caused by the default PHP configuration limits the size of uploaded files. To change it, you need to change the following variables in php.ini:

```
upload_max_filesize = 30M
post_max_size = 30M
```

Lastly, you must restart the web server for the changes to take effect.
