### ISSUE TITLE
404 Install Not Found🐛 [Bug Report]: 

### ISSUE THREAD

**Issue by nyilasviktor0625** [WoW-CMS/BlizzCMS#133]
### BlizzCMS Version

2.0.0 Beta V3

### Emulator

AzerothCore

### PHP Version

PHP 8.1

### Operating system

Linux

### Web server

Apache

### Database

MariaDb

### What happened?

Everything was installed according to the settings described on the page, Php8.1-json not found. Apache2 modules have been enabled. Composer ran without error. Still does not bring up the Install page
![kép](https://github.com/WoW-CMS/BlizzCMS/assets/55741832/4a7ee34d-978f-4af0-bed1-d79fabcbaf28)

### How can the issue be reproduced?

I tried several times and always got here

### Screenshots

![kép](https://github.com/WoW-CMS/BlizzCMS/assets/55741832/214a041b-9743-461e-9b14-31599cffbbda)
![kép](https://github.com/WoW-CMS/BlizzCMS/assets/55741832/2496256e-540a-4a34-9eae-c18f6fe23d36)

**Comment by Ps3mk18** [comment]
Same problem. How to solve this`?
