### ISSUE TITLE
💡 [Feature Request]: Sitemap 

### ISSUE THREAD

**Issue by v2wow** [WoW-CMS/BlizzCMS#134]
### Feature

Hope to add the function of site map

### Feature Purpose

Make it easier for search engines to crawl the website

**Comment by sayghteight** [comment]
![image](https://github.com/WoW-CMS/BlizzCMS/assets/13646300/2827490c-e2c5-4968-9645-add1c23a5b3a)

We are already working on adding the module in v2, I hope to finish it this weekend.

**Comment by sayghteight** [comment]
Feature completed in https://github.com/WoW-CMS/bm-sitemap
