### ISSUE TITLE
🐛 [Bug Report]: Trinity core, master branch not supported

### ISSUE THREAD

**Issue by wolone** [WoW-CMS/BlizzCMS#137]
### BlizzCMS Version

v2.0.0-beta3

### Emulator

TrinityCore

### PHP Version

PHP 8.1

### Operating system

Linux, Windows

### Web server

Apache

### Database

MySQL 8.0.31

### What happened?

The newly created and registered accounts during installation are unable to log in to the game properly, and the data in the table seems to be inconsistent with the account information registered on the trinitycore console
![image](https://github.com/WoW-CMS/BlizzCMS/assets/48593469/64a38517-6e65-496b-8b1e-73c4b77f3e57)

### How can the issue be reproduced?

全新的trinitycore,master分支

**Comment by wolone** [comment]
New trinity core, master branch

**Comment by sayghteight** [comment]
Duplicate issue #140
