### ISSUE TITLE
[Bug Report]: cMangos

### ISSUE THREAD

**Issue by miraco** [WoW-CMS/BlizzCMS#28]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Localhost

### Which emulator are you using and which version?

MaNGOS

### Describe the bug

With https://github.com/cmangos/mangos-tbc/commit/a88c9d5fd3e1b99a77184e989497e90d03aec313#diff-64b23ee7ecc4085ea5f9c306d270e6bc9331fb63c3d71b5d53cc78ebfe2d80a6
cmangos stoped using last_ip and last_login
When using cmangos and trying to login you will get error

`
A Database Error Occurred

Error Number: 1054

Unknown column 'last_login' in 'field list'

SELECT `last_login` FROM `account` WHERE `id` = '5'

Filename: C:/xampp/htdocs/system/database/DB_driver.php

Line Number: 691
`

### How can I reproduce the problem?

Install CMS and use newest cMangos realmd DB.
Login / Register -> get the error.

**Comment by pangolp** [comment]
Why did you close the topic?

**Comment by miraco** [comment]
cause i thought https://github.com/WoW-CMS/support/issues/14 is the right place to post issues :<

**Comment by pangolp** [comment]
Never compile CMaNGOS. At the moment only AzerothCore. I will try to see if I can compile it in docker.
