### ISSUE TITLE
[Bug Report]: Call to undefined method Auth_model::Account()

### ISSUE THREAD

**Issue by bronzato** [WoW-CMS/BlizzCMS#32]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

When you try to recovery an account this you get this error (looking into the networking tab on developers mode (F12) in the browser)

![image](https://user-images.githubusercontent.com/6419694/149147142-2c5d1dce-b836-4d5b-9074-f9c2bad30f10.png)

![image](https://user-images.githubusercontent.com/6419694/149147195-beee3187-52d8-4297-bb79-7b6da64166df.png)

Searching in the files, i found the function sendpassword from User_model.php and here is the code of line 280

$newpassI = $this->wowauth->Account($username, $newpass);

but i didnt find the wow->Account in the Auth_model.php

![image](https://user-images.githubusercontent.com/6419694/149147619-c3a40666-6a20-43c8-bf9d-b8a8294736d0.png)

Another observation is the newpass dont have the srp6 implemented.

### How can I reproduce the problem?

1 - enable the recovery option on modules settings
2 - configure an SMTP server
3 - 4 - Press F12 in your browser and put in networking tab
4 - try recovery an account
5 - click on the forgotpassword in red on the list on networking tab

**Comment by sayghteight** [comment]
The recovery password is a pending issue to fix to the new version of tables, so we still have to work on it. I would suggest removing it while we work on this.

**Comment by bronzato** [comment]
i fixed for SRP6 version of tables, i'll not upload a new PR because idk how fix the battlenet versions, but i'll share the code here if you want update your code.

![image](https://user-images.githubusercontent.com/6419694/149684154-5a85940c-e960-4289-bfb0-d89640784ab5.png)

I removed the commented part for the code work for me.

**Comment by pangolp** [comment]
Hello, it would be necessary to test the code. Maybe it can be applied, while doing the rest of the implementations. I'm missing emulators, to test some features, I only usually do it with the latest version of AzerothCore that uses SRP6. The rest of emulators, I don't know how they work.

**Comment by kotishe** [comment]
I propose to use a different password recovery model, we simply send a link to the user with authorization and the ability to change the password on a separate page, this is done on some sites.

**Comment by pangolp** [comment]
> I propose to use a different password recovery model, we simply send a link to the user with authorization and the ability to change the password on a separate page, this is done on some sites.

Yes, in fact, there are several things that can be done in this regard. As long as it solves the problem, the method really seems indistinct to me. I prefer it to be something automatic, so that no one is controlling or approving, but it depends on whether they have a mail server that sends the information correctly.
