### ISSUE TITLE
[Suggest]: New Payment options

### ISSUE THREAD

**Issue by scarecr0w12** [WoW-CMS/BlizzCMS#33]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

Add additional payment features such as Stripe, ApplePay, and most importantly, Coinbase or another Crypto payment sysetm.

### Additional context.

Additional payment methods outside of paypal would be hugely beneficial to other users of this script who either may not be able to use Paypal, or have players unable to pay with Paypal due to location or other issues.

**Comment by pangolp** [comment]
Hi, I'm looking forward to adding new payment methods, the truth is that I'm not lacking. But for the moment, we have not been able to do it. Anyway, the suggestion is valid and is present in the to-do list. Thanks.
