### ISSUE TITLE
[Suggest]: Bug Report comments

### ISSUE THREAD

**Issue by scarecr0w12** [WoW-CMS/BlizzCMS#34]
### Is your feature request related to a problem? Please describe.

No problem

### Describe the solution you'd like.

Add a comments and reply system, similar to a forum post/reply, to the bug report area to allow for further communication between the reporter and host. This would allow for more things to be solved in a better way.

### Describe alternatives you've considered.

Utilizing forum posts, but those are not private.

**Comment by pangolp** [comment]
A good idea, although there are many tools that can do that job and that are created specifically to support it. But we will see if we can do some implementation. Thanks for the suggestion.

**Comment by sayghteight** [comment]
Finished feat, on November 1 it will be published with the new version.
