### ISSUE TITLE
[Bug Report]: Missing donation log view

### ISSUE THREAD

**Issue by scarecr0w12** [WoW-CMS/BlizzCMS#35]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Web Hosting

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

When going to view Donation/Vote logs in the admin dashboard, it loads to https://www.theegn.com/en/admin/logs But provides a 404 

### How can I reproduce the problem?

Attempt viewing donation/vote point logs from the admin interface.

**Comment by pangolp** [comment]
Right, we currently have a problem on that, I will try to check the cause of it. Thanks for the report.
