### ISSUE TITLE
[Bug Report]: Migration Tool doesnt work

### ISSUE THREAD

**Issue by NeoTwoK** [WoW-CMS/BlizzCMS#47]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

The problem occurs after exiting the migration / installation tool. After clicking on "Write Settings File", you end up on the path "https://xXx.de/en". However, this folder does not exist in the BlizzCMS folder structure.
I tried it both with an IIS server and most recently on an Apache server. Always the same error.
But the config is written. He writes the database information in "...\blizzcms\application\config\database.php". That seems to work. 

### How can I reproduce the problem?

Try to install BlizzCMS ;-) 

### Screenshots

![grafik](https://user-images.githubusercontent.com/94994666/160792164-16be54a7-43f0-451f-8a8d-ec56c9c41151.png)
![grafik](https://user-images.githubusercontent.com/94994666/160791543-b7a7c8cd-c0d1-4c91-b609-abf40aee68d0.png)

**Comment by pangolp** [comment]
I don't know how IIS works, because I haven't really used it. I usually use apache or ngnix. But you should check just in case, the mod_rewrite, or if there is something similar inside IIS because I think it is failing. Keep me posted, if that's it or if the error persists.
