### ISSUE TITLE
[Bug Report]: a little help

### ISSUE THREAD

**Issue by Dude100** [WoW-CMS/BlizzCMS#48]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

https://pastebin.com/wfQmyxEB

**Comment by pangolp** [comment]
Check, if you have the realm configuration right. It seems that the connection may be failing. If it is not that, we will continue to see how to solve it. To check the soap connection, you can use `/en/admin/checksoap` with an administrator account. You can check the wiki article. https://wow-cms.github.io/wiki/create-a-realm

**Comment by Dude100** [comment]
SoapFault exception: [HTTP] Could not connect to host in /var/www/dragonfirebg.net/application/models/Realm_model.php:263 Stack trace: #0 [internal function]: SoapClient->__doRequest('__call('executeCommand', Array) #2

realm info is right user pass port etc..

**Comment by Dude100** [comment]
1: new install 
2: /en/admin/checksoap ---> AzerothCore rev. 48fccc851d84+ 2022-04-06 05:48:06 -0300 (master branch) (Unix, Release, Static) Connected players: 0. Characters in world: 0. Connection peak: 0. Server uptime: 3 hour(s) 13 minute(s) 8 second(s) Update time diff: 10ms, average: 10ms.
3: php -v = PHP 7.1.33-44+0~20211119.61+debian10~1.gbp448fbe (cli) (built: Nov 19 2021 06:42:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33-44+0~20211119.61+debian10~1.gbp448fbe, Copyright (c) 1999-2018, by Zend Technologies
4.1: php = php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
ps
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

https://gyazo.com/4cd812534c8d36d0d3b00b34155a21c3
https://gyazo.com/d39548f73152c32a3d5703222cd024fe

**Comment by pangolp** [comment]
Try using php version 7.3 or 7.4 just in case the problem persists.
