### ISSUE TITLE
[Bug Report]:  SYSTEM

### ISSUE THREAD

**Issue by Rimovals2** [WoW-CMS/BlizzCMS#50]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Web Hosting

### Which emulator are you using and which version?

OregonCore (talamortis repo)

### Describe the bug

1. When buying items there is no verification that SOAP is enabled on the server. So it takes your money but you get nothing.

2. If you have reCaptche enabled, there is no need to confirm when you register or log in.

3. PvP Statistics

> An uncaught Exception was encountered
> Type: Error
> 
> Message: Call to a member function result() on bool
> 
> Filename: /web/htdocs6/web//home/www/application/modules/pvp/views/index.php
> 
> Line Number: 30
> 
> Backtrace:
> 
> File: /web/htdocs6/web//home/www/application/third_party/MX/Loader.php
> Line: 588
> Function: include
> 
> File: /web/htdocs6/web//home/www/application/third_party/MX/Loader.php
> Line: 506
> Function: _ci_load
> 
> File: /web/htdocs6/web//home/www/application/libraries/Template.php
> Line: 802
> Function: view
> 
> File: /web/htdocs6/web//home/www/application/libraries/Template.php
> Line: 763
> Function: _load_view
> 
> File: /web/htdocs6/web/home/www/application/libraries/Template.php
> Line: 286
> Function: _find_view
> 
> File: /web/htdocs6/web/home/www/application/modules/pvp/controllers/Pvp.php
> Line: 62
> Function: build
> 
> File: /web/htdocs6/web//home/www/index.php
> Line: 320
> Function: require_once

**Comment by pangolp** [comment]
I was aware of the Recaptcha thing, because a friend mentioned that error to me. Regarding the store, before adding the items, it should be verified that everything is well configured, anyway, I will check if something can be done about it. But as I always test before adding items, I have never had this problem before.

**Comment by Rimovals2** [comment]
> I was aware of the Recaptcha thing, because a friend mentioned that error to me. Regarding the store, before adding the items, it should be verified that everything is well configured, anyway, I will check if something can be done about it. But as I always test before adding items, I have never had this problem before.

Yes, it will not do a check that the soap is active.

**Comment by pangolp** [comment]
We have several things to improve within the CMS, that is a reality. Some of them we are doing as they are reported, but others take a little longer. The code was practically inherited from version 1, and so my colleagues were working on a remake, but there are only 2 people working on the project and there are many features that have to be implemented.

**Comment by sayghteight** [comment]
We are aware of this bug in the PvP module, and we will be checking to make it compatible with other emulators.
