### ISSUE TITLE
[Bug Report]: Error Number: 1054  Unknown column 'v' in 'field list'

### ISSUE THREAD

**Issue by Kupers** [WoW-CMS/BlizzCMS#52]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

TrinityCore 9.2.0

A Database Error Occurred
Error Number: 1054

Unknown column 'v' in 'field list'

INSERT INTO `account` (`username`, `v`, `s`, `email`, `expansion`, `last_ip`) VALUES ('san4o', '7942135654656456564564565466BB', '7E6E2D191AC5656456456456F3CD1E', 'san4o@gmail.com', '8', '127.0.0.1')

Filename: modules/user/models/User_model.php

Line Number: 202

### How can I reproduce the problem?

https://github.com/TrinityCore/TrinityCore/blob/master/sql/base/auth_database.sql

CREATE TABLE `account` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Identifier',
  `username` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `salt` binary(32) NOT NULL,
  `verifier` binary(32) NOT NULL,
  `session_key_auth` binary(40) DEFAULT NULL,
  `session_key_bnet` varbinary(64) DEFAULT NULL,
  `totp_secret` varbinary(128) DEFAULT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `reg_mail` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `joindate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_ip` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '127.0.0.1',
  `last_attempt_ip` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '127.0.0.1',
  `failed_logins` int unsigned NOT NULL DEFAULT '0',
  `locked` tinyint unsigned NOT NULL DEFAULT '0',
  `lock_country` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '00',
  `last_login` timestamp NULL DEFAULT NULL,
  `online` tinyint unsigned NOT NULL DEFAULT '0',
  `expansion` tinyint unsigned NOT NULL DEFAULT '8',
  `mutetime` bigint NOT NULL DEFAULT '0',
  `mutereason` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `muteby` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `locale` tinyint unsigned NOT NULL DEFAULT '0',
  `os` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `recruiter` int unsigned NOT NULL DEFAULT '0',
  `battlenet_account` int unsigned DEFAULT NULL,
  `battlenet_index` tinyint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_username` (`username`),
  UNIQUE KEY `uk_bnet_acc` (`battlenet_account`,`battlenet_index`),
  CONSTRAINT `fk_bnet_acc` FOREIGN KEY (`battlenet_account`) REFERENCES `battlenet_accounts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Account System';

**Comment by pangolp** [comment]
If you are using a Shadowlands TrinityCore, be sure to choose the BNET option. Since it uses that form for account registration. You can modify it within the configuration file. https://github.com/WoW-CMS/BlizzCMS/blob/master/application/config/blizzcms.php#L55
