### ISSUE TITLE
I cannot access the database.

### ISSUE THREAD

**Issue by jhoulove** [WoW-CMS/BlizzCMS#53]
![image](https://user-images.githubusercontent.com/19393399/164977779-f318877b-1d22-42b9-b353-43b3d646647d.png)

> all settings are default

**Comment by pangolp** [comment]
This error occurs if you do not have a virtualhost created. Check this document, so you can create one, and then try again: https://stackoverflow.com/questions/2658173/set-up-apache-virtualhost-on-windows
