### ISSUE TITLE
[Bug Report]: Message: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by Painwithin** [WoW-CMS/BlizzCMS#54]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Localhost

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

After filling out the information to log into the databases i get several errors.

Error 1:

A PHP Error was encountered

Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: core/MY_Lang.php

Line Number: 97

Backtrace:

File: /home/painwithin/public_html/register/application/core/MY_Lang.php
Line: 97
Function: _error_handler

File: /home/painwithin/public_html/register/index.php
Line: 320
Function: require_once

Error 2:

A PHP Error was encountered

Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: core/MY_Lang.php

Line Number: 109

Backtrace:

File: /home/painwithin/public_html/register/application/core/MY_Lang.php
Line: 109
Function: _error_handler

File: /home/painwithin/public_html/register/index.php
Line: 320
Function: require_once

Error 3

A PHP Error was encountered

Severity: Notice

Message: Trying to access array offset on value of type null

Filename: core/MY_Lang.php

Line Number: 109

Backtrace:

File: /home/painwithin/public_html/register/application/core/MY_Lang.php
Line: 109
Function: _error_handler

File: /home/painwithin/public_html/register/index.php
Line: 320
Function: require_once

and Error 4:

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/painwithin/public_html/register/system/core/Exceptions.php:271)

Filename: core/MY_Lang.php

Line Number: 119

Backtrace:

File: /home/painwithin/public_html/register/application/core/MY_Lang.php
Line: 119
Function: header

File: /home/painwithin/public_html/register/index.php
Line: 320
Function: require_once

### How can I reproduce the problem?

I am unsure how i can produce a way for someone else to get these errors, i simply filled in the form for the configuration of the database and then these errors pop up, im not sure if its something im somehow doing wrong or not.

To add some additional information, my WoW Server is on a Windows VM and the web server is on a linux VM "i use proxmox" so i put the IP information in accordingly to the auth and the database i made for the site.

**Comment by pangolp** [comment]
Do you have communication between the two machines? I ask just in case, because it may be a port issue. I don't know in which part of the site generates the error, when entering to which functionality?

**Comment by Painwithin** [comment]
Yes I do. I use another reg page atm and it works just not sure why this one isnt.

**Comment by Painwithin** [comment]
Also, does this error mean there is an issue with it communicating with the database? if so then i will have to dig deeper into what the issue is as it does not give an error message other then the ones i posted.

**Comment by pangolp** [comment]
What version of PHP 7 are you using? Just in case, try to use version 7.3 or 7.4. At the moment version 8 is not supported, so try to use the latest available version 7. Please let me know if the problem persists, to see what we can find out about it.
