### ISSUE TITLE
[Help Wanted]: Updated Documentation, Discord links?

### ISSUE THREAD

**Issue by Xeliaa** [WoW-CMS/BlizzCMS#58]
### What happened?

Aloha, I managed to get BlizzCMS Working on an IIS Server, URL Rewrite is a Requirement to add to iis, But i your documents links are dead as well as Discord links on here, on kofi and on the main website are all invalid. I see that the page has a Admin CP but with out documentation im having alittle trouble gaining full controll over the CMS, Also how do i make it so it will accept characters like !! in the password, it only asks for Alpha Numerics

### Version

1.0.7.8 (Recommended)

### Browser

Firefox

### What version of PHP are you running?

PHP7

**Comment by Kyyteo** [comment]
I'm in the same boat as you @Xeliaa . So far I'm loving the CMS. It would be nice to see the documentation, and definitely (especially) Have complex passwords for account creation. I noticed you can go into the User settings page and THEN change it to a complex password though.

**Comment by Kyyteo** [comment]
> Can you install successfully?

Yes. Installing is no problem for me. Are you having issues?

**Comment by yuanf225** [comment]
I use nginx+php7.4 and I can't continue the installation after entering the corresponding db information in the first step of the installation page. There are php extensions. I don't know what else I am missing.

**Comment by sayghteight** [comment]
Unfortunately we can't always give all the support we want to different webservers, the documentation is being worked on.

What problems does Nginx give you? I leave the thread open.
