### ISSUE TITLE
[Bug Report]: Multiple accounts on the same IP - can't log in on old ones

### ISSUE THREAD

**Issue by maradaka** [WoW-CMS/BlizzCMS#60]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Website

### Where are you trying to install the CMS?

Localhost

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

When you create multiple accounts from the localhost, I guess it's working with any IP, you can log in on website only on the last one created because the passwords from the old ones are not recognized anymore. The ingame account it's working just fine.

### How can I reproduce the problem?

Try to create multiple accounts from the same IP and then log in on the first ones created.

### Screenshots

https://user-images.githubusercontent.com/32881224/177486819-a2f6fc56-0a36-4e96-b7c5-c0d384391a1e.png

The credentials are correct!

**Comment by AvoelDev** [comment]
Then you made a mistake setting it up correctly.

I tried multiple times to reproduce your bug but nothing.

Create a few accoutns and all of them work ( on the website & ingame )

**Comment by sayghteight** [comment]
We are working on making some fixes with the Auth model, this is because there were times when it generated errors. Anyway, from my local I have been testing Trinity Core and I have generated different accounts and they have always worked.
