### ISSUE TITLE
[Bug Report]: PHP Error 

### ISSUE THREAD

**Issue by Awixs777** [WoW-CMS/BlizzCMS#61]
### What operating system are you using?

Windows

### What version of PHP do you use?

Other

### Where did you get the CMS code?

Website

### Where are you trying to install the CMS?

Web Hosting

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

Hello. An error occurs when using voting in your personal account. 
PHP version 7.3.33 , all extensions are active.

### How can I reproduce the problem?

Vote in your personal account.

### Screenshots

![Screenshot_6](https://user-images.githubusercontent.com/47874183/184322961-912a2763-4342-4606-b1de-c7ef0102bc22.png)

helpers/url_helper.php
![Screenshot_1](https://user-images.githubusercontent.com/47874183/184328771-d21cc5f6-edad-49b6-b2a4-934b7370cbac.png)

**Comment by sayghteight** [comment]
I will try to reproduce this error, with a version of PHP7, as soon as I know something I will update this thread.

**Comment by sayghteight** [comment]
After testing, I have not been able to replicate the error in my local works well. Try downloading this repository and checking that you don't have something old.
