### ISSUE TITLE
[Bug Report]: SMTP not working

### ISSUE THREAD

**Issue by kaneit** [WoW-CMS/BlizzCMS#62]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Web Hosting

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

I've filled in the correct details for the email system. i've selected enable for account activation.

Accounts get created but no emails get sent out.

Also when sending recovery emails. they do not send out emails either.
i've tried using SSL and port 465 and TLS on port 587.

i've filled in the following
SMTP|
SMTP Hostname
SMTP Port
SSL/TLS
SMTP Username
SMTP Password
Sender Email
Sender Name

and can't get it to work

I am using Cpanel and i am the only administrator and i manage it myself. and i've not seeing a single email get sent out.

**Comment by Re3os** [comment]
22.08.2023....mail not work.
issue Aug 19, 2022 .
@stefan3126 smpt dont work this repo
