### ISSUE TITLE
[Bug Report]: Tickets Displaying Errors in Left hand panel

### ISSUE THREAD

**Issue by kaneit** [WoW-CMS/BlizzCMS#63]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Web Hosting

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

After a fresh install on my webhost with all modules required to run.

i'm facing errors that display in the left hand panel.
`A PHP Error was encountered
Severity: Notice
Message: Undefined variable: realmsList
Filename: tickets/manage_tickets.php
Line Number: 15
Backtrace:

File: /home/hidden/public_html/application/modules/admin/views/tickets/manage_tickets.php
Line: 15
Function: _error_handler

File: /home/hidden/public_html/application/third_party/MX/Loader.php
Line: 588
Function: include

File: /home/hidden/public_html/application/third_party/MX/Loader.php
Line: 506
Function: _ci_load

File: /home/hidden/public_html/application/libraries/Template.php
Line: 802
Function: view

File: /home/hidden/public_html/application/libraries/Template.php
Line: 763
Function: _load_view

File: /home/hidden/public_html/application/libraries/Template.php
Line: 286
Function: _find_view

File: /home/hidden/public_html/application/modules/admin/controllers/Admin.php
Line: 1490
Function: build

File: /home/hidden/public_html/index.php
Line: 320
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: tickets/manage_tickets.php

Line Number: 15

Backtrace:

File: /home/hidden/public_html/application/modules/admin/views/tickets/manage_tickets.php
Line: 15
Function: _error_handler

File: /home/hidden/public_html/application/third_party/MX/Loader.php
Line: 588
Function: include

File: /home/hidden/public_html/application/third_party/MX/Loader.php
Line: 506
Function: _ci_load

File: /home/hidden/public_html/application/libraries/Template.php
Line: 802
Function: view

File: /home/hidden/public_html/application/libraries/Template.php
Line: 763
Function: _load_view

File: /home/hidden/public_html/application/libraries/Template.php
Line: 286
Function: _find_view

File: /home/hidden/public_html/application/modules/admin/controllers/Admin.php
Line: 1490
Function: build

File: /home/hidden/public_html/index.php
Line: 320
Function: require_once
`

### How can I reproduce the problem?

for me.

i simply logged into admin panel and selected tickets.
and the errors displayed on the left panel

### Screenshots

![Screenshot 2022-08-19 085150](https://user-images.githubusercontent.com/75580409/185571303-6f4dc70f-1114-4986-bdce-1fd9aae012c5.png)

**Comment by sayghteight** [comment]
About the Ticket module

This module was created to support 3.3.5a the new versions of TrinityCore does not bring or provide the possibility of creating in-game tickets, so the maintenance of said module within the website has been ruled out.
