### ISSUE TITLE
[Help Wanted]: 

### ISSUE THREAD

**Issue by delyura** [WoW-CMS/BlizzCMS#70]
### What happened?

Installation problem!
I try to create a user, but I get an error. 
![image](https://user-images.githubusercontent.com/25474817/190592072-a5686135-3985-4c2f-aeef-d499b57a9c87.png)
![image](https://user-images.githubusercontent.com/25474817/190592218-c8f829a3-a0e0-4e97-b69c-4ed2e0f42546.png)
How to create a table account correctly? Which columns?

### Version

1.0.7.8 (Recommended)

### Browser

Chrome

### What version of PHP are you running?

PHP7

**Comment by delyura** [comment]
any help?

**Comment by sayghteight** [comment]
You have not configured the databases correctly, check the configuration of the second database in application/config/database.php it should be pointing to your Auth table not to BlizzCMS.
