### ISSUE TITLE
[Bug Report]: Recaptcha / mail verification not working (getting bombed)

### ISSUE THREAD

**Issue by luckie12** [WoW-CMS/BlizzCMS#71]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 8.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

The recaptcha is configured correctly, and the mail verification too. But even with both on they omit the login / registering process.

Even without filling in the recaptcha or the verification mail you can register and login. This results in some idiots "bombing" our form with fake info (look at screenshots)

### How can I reproduce the problem?

Enable the recaptcha and configure the mail verification and see for yourself

### Screenshots

![unknown](https://user-images.githubusercontent.com/20926351/191338656-65efea7f-b507-4a20-80ad-391b301712eb.png)
![unknown](https://user-images.githubusercontent.com/20926351/191338682-250d0096-3f57-4231-bbfb-6f10d81933a5.png)
![image](https://user-images.githubusercontent.com/20926351/191338976-ce1717ce-b180-4d21-a8c5-bfd93f5e7fe3.png)

**Comment by sayghteight** [comment]
I'll check the code to see what happens.
