### ISSUE TITLE
[QUESTION] Update the discord url on the website

### ISSUE THREAD

**Issue by luckie12** [WoW-CMS/BlizzCMS#77]
I would like to join the discord channel but the URL expired on your website ^^

**Comment by mitko-janeski** [comment]
> I would like to join the discord channel but the URL expired on your website ^^

While installing on the migration page on the top right there is a discord link but the URL is wrong it says
"https://discord.wow-cms-com/"

Should be changed to
"https://discord.wow-cms.com/"

**Comment by sayghteight** [comment]
Fixed in https://github.com/WoW-CMS/BlizzCMS/commit/8a9c510002b4112340ba25894de071b7203d1cea 

Thanks for Report
