### ISSUE TITLE
[Bug Report]: POST https://xxxx.org/en/forgotpassword 500

### ISSUE THREAD

**Issue by stylo019** [WoW-CMS/BlizzCMS#84]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

Salut,

j'ai configuré les options SMTP, mais ca ne fonctionne pas, j'ai essayé d'autre option et ça ne fonctionne toujours pas.

Je reçois l'erreur 500. Impossible de récupérer le mot de passe perdu…

Vous pourriez m'aider svp ?

### Screenshots

![image](https://user-images.githubusercontent.com/32231047/195586286-603c033c-de89-4e27-8174-a73fbacbee8a.png)

**Comment by sayghteight** [comment]
We are working on refactoring the code that has to do with sending passwords and activating them.

**Comment by stylo019** [comment]
Ok thanks :)
