### ISSUE TITLE
[Suggest]: Currencies

### ISSUE THREAD

**Issue by Insta-Dev** [WoW-CMS/BlizzCMS#88]
### Is your feature request related to a problem? Please describe.

Adjust currencies symbols according to the selected currency typed in `settings/module`
I can say my "basic" pack costs 5 Euros and it will still show USD symbol on the website.

### Describe the solution you'd like.

I had to manually adjust it within the site files, from $ to €

### Describe alternatives you've considered.

The same can be said about British Pounds, or any other currency basically. If we can have a list of currencies and symbols (or at least the option to select what we show on the store page) that'd be awesome!

**Comment by sayghteight** [comment]
The suggestion will be reviewed and addressed in the 1.0.8.1 milestone.

**Comment by sayghteight** [comment]
Finished option has been added to the administration panel, on November 1 it will be published with the new version.
